/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hojarepasoso;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jose-PC
 */
public class primario extends javax.swing.JFrame {

    Hilo x = new Hilo(1);
    HiloABC y = new HiloABC(2);

    public primario() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iniciarboton = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        cajatxt = new javax.swing.JTextField();
        inicioABC = new javax.swing.JButton();
        textoabc = new javax.swing.JTextField();
        ABC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciarboton.setText("Inciar");
        iniciarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarbotonActionPerformed(evt);
            }
        });

        text.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        text.setText("0");

        cajatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatxtActionPerformed(evt);
            }
        });

        inicioABC.setText("iniciar");
        inicioABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioABCActionPerformed(evt);
            }
        });

        ABC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ABC.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iniciarboton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inicioABC)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cajatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(textoabc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ABC)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoabc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarboton)
                    .addComponent(inicioABC))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatxtActionPerformed

    private void iniciarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarbotonActionPerformed

        if (x.isAlive() == false) {
            String j = cajatxt.getText();
            int n = Integer.parseInt(j);
            x = new Hilo(n);
            x.start();
        }


    }//GEN-LAST:event_iniciarbotonActionPerformed

    private void inicioABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioABCActionPerformed

        if (y.isAlive() == false) {
            String j = textoabc.getText();
            switch (j) {
                case "a":
                    y = new HiloABC(1);
                    break;
                case "b":
                    y = new HiloABC(2);
                    break;
                case "c":
                    y = new HiloABC(3);

                    break;
                case "d":
                    y = new HiloABC(4);

                    break;
                case "e":
                    y = new HiloABC(5);

                    break;
                case "f":
                    y = new HiloABC(6);

                    break;
                case "g":
                    y = new HiloABC(7);

                    break;
                case "h":
                    y = new HiloABC(8);

                    break;
                case "i":
                    y = new HiloABC(9);

                    break;
                case "j":
                    y = new HiloABC(10);

                    break;
                case "k":
                    y = new HiloABC(11);

                    break;
                case "l":
                    y = new HiloABC(12);

                    break;
                case "m":
                    y = new HiloABC(13);

                    break;
                case "n":
                    y = new HiloABC(14);

                    break;
                case "o":
                    y = new HiloABC(15);

                    break;
                case "p":
                    y = new HiloABC(16);

                    break;
                case "q":
                    y = new HiloABC(17);

                    break;
                case "r":
                    y = new HiloABC(18);

                    break;
                case "s":

                    y = new HiloABC(19);
                    break;
                case "t":
                    y = new HiloABC(20);

                    break;
                case "u":
                    y = new HiloABC(21);

                    break;
                case "v":
                    y = new HiloABC(22);

                    break;
                case "w":
                    y = new HiloABC(23);

                    break;
                case "x":
                    y = new HiloABC(24);

                    break;
                case "y":
                    y = new HiloABC(25);

                    break;
                case "z":
                    y = new HiloABC(26);

                    break;

            }
            y.start();

        }


    }//GEN-LAST:event_inicioABCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primario().setVisible(true);
            }
        });
    }

    public class Hilo extends Thread {

        int cont = 0;

        public Hilo(int aux) {
            this.cont = aux;
        }

        @Override
        public void run() {
            while (cont <= 100) {
                text.setText(String.valueOf(cont));
                cont++;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(primario.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        }
    }

    public class HiloABC extends Thread {

        int cont = 0;

        public HiloABC(int aux) {
            this.cont = aux;
        }
        public String letra(int a){
           a=cont;
           String aux="";
            switch(a){
                case 1:
                   aux="a";
                    break;
               case 2:
                   aux="b";
                    break;
               case 3:
                   aux="c";
                    break;
               case 4:
                   aux="d";
                    break;
               case 5:
                   aux="e";
                    break;
               case 6:
                   aux="f";
                    break;
               case 7:
                   aux="g";
                    break;
               case 8:
                   aux="h";
                    break;
               case 9:
                   aux="i";
                    break;
               case 10:
                   aux="j";
                    break;
               case 11:
                   aux="k";
                    break;
               case 12:
                   aux="l";
                    break;
               case 13:
                   aux="m";
                    break;
               case 14:
                   aux="n";
                    break;
               case 15:
                   aux="o";
                    break;
               case 16:
                   aux="p";
                    break;
               case 17:
                   aux="q";
                    break;
               case 18:
                   aux="r";
                    break;
               case 19:
                   aux="s";
                    break;
               case 20:
                   aux="t";
                    break;
               case 21:
                   aux="u";
                    break;
               case 22:
                   aux="v";
                    break;
               case 23:
                   aux="w";
                    break;
               case 24:
                   aux="x";
                    break;
               case 25:
                   aux="y";
                    break;
               case 26:
                   aux="z";
                    break;
               
          }
         return aux;  
        }
        
        @Override
        public void run() {
            while (cont <= 26) {
                ABC.setText(letra(cont));
                
                cont++;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(primario.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ABC;
    private javax.swing.JTextField cajatxt;
    private javax.swing.JButton iniciarboton;
    private javax.swing.JButton inicioABC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    private javax.swing.JTextField textoabc;
    // End of variables declaration//GEN-END:variables
}
