/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usodehilos;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jose-PC
 */
public class primario extends javax.swing.JFrame {
    Hilo x=new Hilo(1);
    HiloABC y=new HiloABC(2);
    public primario() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iniciarboton = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        cajatxt = new javax.swing.JTextField();
        inicioABC = new javax.swing.JButton();
        textoabc = new javax.swing.JTextField();
        textoABC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        iniciarboton.setText("Inciar");
        iniciarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarbotonActionPerformed(evt);
            }
        });

        text.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        text.setText("0");

        cajatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajatxtActionPerformed(evt);
            }
        });

        inicioABC.setText("iniciar");
        inicioABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioABCActionPerformed(evt);
            }
        });

        textoABC.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoABC.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(iniciarboton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inicioABC)
                        .addGap(47, 47, 47))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cajatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(textoabc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoABC)
                        .addGap(66, 66, 66))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoABC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoabc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarboton)
                    .addComponent(inicioABC))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajatxtActionPerformed

    private void iniciarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarbotonActionPerformed

        if (x.isAlive() == false) {
            String j = cajatxt.getText();
            int n=Integer.parseInt(j);
            x=new Hilo(n);
            x.start();
        }


    }//GEN-LAST:event_iniciarbotonActionPerformed

    private void inicioABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioABCActionPerformed

            if (y.isAlive() == false) {
            String j = textoabc.getText();
            switch(j){
                case "a":
            y=new HiloABC(1);        
                    break;
                case "b":
                    
                    break;
                case "c":
                    
                    break;
                case "d":
                    
                    break;
                case "e":
                    
                    break;
                case "f":
                    
                    break;
                case "g":
                    
                    break;
                case "h":
                    
                    break;
                case "i":
                    
                    break;
                case "j":
                    
                    break;
                case "k":
                    
                    break;
                case "l":
                    
                    break;
                case "m":
                    
                    break;
                case "n":
                    
                    break;
                case "p":
                    
                    break;
                case "q":
                    
                    break;
                case "r":
                   
                    break;
                case "s":
                    
                    break;
                case "t":
                    
                    break;
                case "v":
                    
                    break;
                case "w":
                    
                    break;
                case "x":
                    
                    break;
                case "y":
                    
                    break;
                case "z":
                    
                    break;
            }
            y.start();
            
            }


    }//GEN-LAST:event_inicioABCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(primario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new primario().setVisible(true);
            }
        });
    }

    public class Hilo extends Thread {

        int cont = 0;

        public Hilo(int aux) {
            this.cont = aux;
        }

        @Override
        public void run() {
            while (cont <= 100) {
                text.setText(String.valueOf(cont));
                cont++;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(primario.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        }
    }
    
    public class HiloABC extends Thread {

        int cont = 0;

        public HiloABC(int aux) {
            this.cont = aux;
        }
      
        
        @Override
        public void run() {
            while (cont <= 26) {
                text.setText(String.valueOf(cont));
                cont++;
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(primario.class.getName()).log(Level.SEVERE, null, ex);

                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajatxt;
    private javax.swing.JButton iniciarboton;
    private javax.swing.JButton inicioABC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    private javax.swing.JLabel textoABC;
    private javax.swing.JTextField textoabc;
    // End of variables declaration//GEN-END:variables
}
